### ISSUE TITLE
With paralellized Celery workers, integrity error on new user registration (not critical)

### ISSUE THREAD

**Issue by alexdlaird** [HeliumEdu/platform#101]
Does not cause any noticable errors, but when a new user is registered, the tasks for recalulcate are sent to a different worker than the task for generating the example schedule. This causes the grade recalculations to attempt work on items that may not have yet been saved, thus the integrity error below is thrown.

```
[Traceback (most recent call last):
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/helium/platform/helium/planner/tasks.py", line 45, in recalculate_course_grade
    gradingservice.recalculate_course_grade(course)
  File "/srv/helium/platform/helium/planner/services/gradingservice.py", line 180, in recalculate_course_grade
    course.save()
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1283, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/venvs/helium_platform/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`platform_prod`.`planner_course`, CONSTRAINT `planner_course_course_group_id_64c1b5bf_fk_planner_c` FOREIGN KEY (`course_group_id`) REFERENCES `planner_coursegroup` (`id`))')](`url`)
```

The CI test `test_api_example_schedule_grades.tavern` does periodically fail for this reason.

**Comment by alexdlaird** [comment]
The above integrity error has been resolved, but grading in the example schedule is still occasionally resolving to incorrect grades.

**Comment by alexdlaird** [comment]
This error actually appears to occur even with sync workers, so perhaps just needs to be further investigated.

A test has been created to validate. In `test_user_registration_imports_example_schedule`, we now check `self.assertEqual(float(category.grade_by_weight), 40.7861)`. However, this value is occassionally `13.725` instead, and the CI test fails intermittently for the same reason.
